// <auto-generated />
using System;
using BookingApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingApp.Api.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingApp.Shared.Models.Doplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("KwotaDoplaty")
                        .HasColumnType("numeric");

                    b.Property<string>("NazwaDoplaty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RezerwacjaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RezerwacjaId");

                    b.ToTable("Doplaty");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LiczbaGwiazdek")
                        .HasColumnType("integer");

                    b.Property<int>("MiejscowoscId")
                        .HasColumnType("integer");

                    b.Property<string>("NazwaHotelu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MiejscowoscId");

                    b.ToTable("Hotele");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresKlienta")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Kraj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kraje");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Miejscowosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KrajId")
                        .HasColumnType("integer");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KrajId");

                    b.ToTable("Miejscowsci");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<int>("TypWyzywieniaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("TypWyzywieniaId");

                    b.ToTable("Oferty");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolaId");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Rezerwacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KlientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KwotaCalkowita")
                        .HasColumnType("numeric");

                    b.Property<int>("LiczbaOsob")
                        .HasColumnType("integer");

                    b.Property<int>("PracownikId")
                        .HasColumnType("integer");

                    b.Property<int>("TerminCenaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("PracownikId");

                    b.HasIndex("TerminCenaId");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.RodzajPokoju", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLiczbaOsob")
                        .HasColumnType("integer");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("RodzajePokojow");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Rola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TypRoli")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.StatusRezerwacji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZmiany")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RezerwacjaId")
                        .HasColumnType("integer");

                    b.Property<int>("StanStatusu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RezerwacjaId");

                    b.ToTable("StatusyRezerwacji");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.TerminCena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaPodstawowa")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataOd")
                        .HasColumnType("date");

                    b.Property<int>("OfertaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OfertaId");

                    b.ToTable("TerminyCeny");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.TypWyzywienia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaWyzywienia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypyWyzywienia");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.ZdjecieHotelu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlZdjecia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ZdjeciaHotelow");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.ZdjeciePokoju", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RodzajPokojuId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlZdjecia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RodzajPokojuId");

                    b.ToTable("ZdjeciaPokojow");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Doplata", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Rezerwacja", "Rezerwacja")
                        .WithMany("Doplaty")
                        .HasForeignKey("RezerwacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezerwacja");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Hotel", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Miejscowosc", "Miejscowosc")
                        .WithMany("Hotele")
                        .HasForeignKey("MiejscowoscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BookingApp.Shared.Models.Adres", "Adres", b1 =>
                        {
                            b1.Property<int>("HotelId")
                                .HasColumnType("integer");

                            b1.Property<string>("KodPocztowy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NazwaUlicy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NumerBudynku")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NumerLokalu")
                                .HasColumnType("text");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotele");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("Adres")
                        .IsRequired();

                    b.Navigation("Miejscowosc");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Miejscowosc", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Kraj", null)
                        .WithMany("Miejscowosci")
                        .HasForeignKey("KrajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Oferta", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Hotel", "Hotel")
                        .WithMany("Oferty")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Shared.Models.TypWyzywienia", "TypWyzywienia")
                        .WithMany("Oferty")
                        .HasForeignKey("TypWyzywieniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("TypWyzywienia");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Pracownik", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Rola", "Rola")
                        .WithMany("Pracownicy")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Rezerwacja", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Shared.Models.Pracownik", "Pracownik")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Shared.Models.TerminCena", "TerminCena")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("TerminCenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Pracownik");

                    b.Navigation("TerminCena");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.RodzajPokoju", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Hotel", "Hotel")
                        .WithMany("RodzajePokojow")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.StatusRezerwacji", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Rezerwacja", "Rezerwacja")
                        .WithMany("Statusy")
                        .HasForeignKey("RezerwacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezerwacja");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.TerminCena", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Oferta", "Oferta")
                        .WithMany("TerminyCeny")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.ZdjecieHotelu", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.Hotel", "Hotel")
                        .WithMany("ZdjeciaHotelu")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.ZdjeciePokoju", b =>
                {
                    b.HasOne("BookingApp.Shared.Models.RodzajPokoju", "RodzajPokoju")
                        .WithMany()
                        .HasForeignKey("RodzajPokojuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RodzajPokoju");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Hotel", b =>
                {
                    b.Navigation("Oferty");

                    b.Navigation("RodzajePokojow");

                    b.Navigation("ZdjeciaHotelu");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Kraj", b =>
                {
                    b.Navigation("Miejscowosci");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Miejscowosc", b =>
                {
                    b.Navigation("Hotele");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Oferta", b =>
                {
                    b.Navigation("TerminyCeny");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Pracownik", b =>
                {
                    b.Navigation("Rezerwacje");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Rezerwacja", b =>
                {
                    b.Navigation("Doplaty");

                    b.Navigation("Statusy");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.Rola", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.TerminCena", b =>
                {
                    b.Navigation("Rezerwacje");
                });

            modelBuilder.Entity("BookingApp.Shared.Models.TypWyzywienia", b =>
                {
                    b.Navigation("Oferty");
                });
#pragma warning restore 612, 618
        }
    }
}
